name: SQL IaaS Extension

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
      - name: Checkout
        uses: actions/checkout@v3
      - run: ./EnableBySubscription.ps1 -SubscriptionList f6e79ccd-3633-4139-ae22-9e5b809085d6
        shell: pwsh
