name: SQL IaaS Extension

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Install Azure cli
#        run: |
 #         sudo apt-get update
   #       sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
   #       sudo mkdir -p /etc/apt/keyrings
    #      curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
   #       sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
   #       AZ_REPO=$(lsb_release -cs)
   #       echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
    #      sudo apt-get update
      #    sudo apt-get install azure-cli
      - uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          enable-AzPSSession: true
   #   - uses: azure/CLI@v1
   #     with:
     #     azcliversion: 2.0.72
  #        inlineScript: |
    #        az account list
      - name: Checkout
        uses: actions/checkout@v3
      - run: ./EnableBySubscription.ps1 -SubscriptionList f6e79ccd-3633-4139-ae22-9e5b809085d6
        shell: pwsh
